Repository ucb-bar/hammer, pull requests merged in 2019-08, with the labels that each got.

#498 Fix typo
  src/hammer-vlsi/defaults.yml
Labels: bug, documentation

#326 Hammer sim
  src/hammer-tech/filters.py
  src/hammer-tech/library_filter.py
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/generate_properties.py
  src/hammer-vlsi/hammer_utils/__init__.py
  src/hammer-vlsi/hammer_vlsi/cli_driver.py
  src/hammer-vlsi/hammer_vlsi/driver.py
  src/hammer-vlsi/hammer_vlsi/hammer_tool.py
  src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
  src/hammer-vlsi/sim/mocksim/__init__.py
  src/hammer-vlsi/sim/mocksim/defaults.yml
  src/hammer-vlsi/test.py
Labels: CurrentTapeout, DO NOT MERGE, enhancement, high priority

#499 asap7 works through par
  src/hammer-vlsi/technology/asap7/asap7.tech.json
  src/hammer-vlsi/technology/asap7/defaults.yml
Labels: enhancement, high priority
