Repository ucb-bar/hammer, pull requests merged in 2019-05, with the labels that each got.

#370 Add Site objects and use Decimal for Site and Stackup
  src/hammer-tech/hammer_tech.py
  src/hammer-tech/schema.json
  src/hammer-tech/stackup.py
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/hammer_utils/__init__.py
  src/hammer-vlsi/hammer_vlsi/hammer_tool.py
  src/hammer-vlsi/tech_test.py
  src/hammer-vlsi/test_tool_utils.py
  src/hammer-vlsi/utils_test.py
Labels: API, floorplan, medium priority

#399 Add some assertions to sanity check the tech plugin
  src/hammer-tech/stackup.py
  src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
Labels: UPF_CPF, bug, low priority, usability

#405 Document Python type of clock constraints
  src/hammer-vlsi/defaults.yml
Labels: documentation

#406 Power straps mode change
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
Labels: beginner PR, very low priority

#408 Remove confusing statement
  src/hammer-vlsi/defaults.yml
Labels: documentation, usability

#412 Don't crash on checking untyped arguments
  src/hammer-vlsi/hammer_utils/__init__.py
  src/hammer-vlsi/utils_test.py
Labels: bug

#398 Implement semi-auto pin placement API
  src/hammer-vlsi/constraints_test.py
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/hammer_vlsi/constraints.py
  src/hammer-vlsi/hammer_vlsi/hammer_tool.py
  src/hammer-vlsi/test.py
Labels: API, enhancement, high priority

#415 Add blockage_spacing to standard cell power strap placement
  src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
  src/hammer-vlsi/par/mockpar/__init__.py
  src/hammer-vlsi/par/nop.py
Labels: UPF_CPF, floorplan, high priority
