Repository ucb-bar/hammer, pull requests merged in 2019-06, with the labels that each got.

#413 Floorplan Constraints Overhaul. Fixes #113 and #376
  src/hammer-tech/hammer_tech.py
  src/hammer-vlsi/cli_driver_test.py
  src/hammer-vlsi/constraints_test.py
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/hammer_utils/__init__.py
  src/hammer-vlsi/hammer_utils/lef_utils.py
  src/hammer-vlsi/hammer_vlsi/constraints.py
  src/hammer-vlsi/hammer_vlsi/driver.py
  src/hammer-vlsi/hammer_vlsi/hammer_tool.py
  src/hammer-vlsi/lef_utils_test.py
  src/hammer-vlsi/tech_test.py
  src/hammer-vlsi/test.py
  src/hammer_config/config_src.py
Labels: medium priority

#421 Fix JSON serialization bug with Decimals
  src/hammer-tech/hammer_tech.py
  src/hammer-vlsi/cli_driver_test.py
  src/hammer-vlsi/hammer_vlsi/cli_driver.py
  src/hammer-vlsi/par/mockpar/__init__.py
  src/hammer-vlsi/tech_test.py
  src/hammer-vlsi/test.py
  src/hammer-vlsi/test_tool_utils.py
  src/hammer_config/config_src.py
  src/hammer_config/yaml2json.py
Labels: bug, high priority

#423 Add an example of how to use master
  src/hammer-vlsi/defaults.yml
Labels: documentation, enhancement

#436 Add a create field
  src/hammer-vlsi/cli_driver_test.py
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/hammer_vlsi/constraints.py
Labels: API, DO NOT MERGE, enhancement, floorplan, medium priority

#437 Indentation helper switch
  src/hammer-vlsi/hammer_vlsi/hammer_tool.py
Labels: DeveloperSupport, enhancement, low priority, usability

#434 Add an additional PCB deliverable that we need for our PCB flow
  src/hammer-vlsi/constraints_test.py
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/hammer_utils/__init__.py
  src/hammer-vlsi/hammer_vlsi/constraints.py
  src/hammer-vlsi/hammer_vlsi/driver.py
  src/hammer-vlsi/pcb/generic/__init__.py
  src/hammer-vlsi/test.py
  src/hammer-vlsi/utils_test.py
Labels: PCB, medium priority

#446 Select DRC checks
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
Labels: enhancement, medium priority, usability

#452 Document DRC rules API
  src/hammer-vlsi/defaults.yml
Labels: documentation, enhancement, usability

#448 First pass at a Makefile generator, fixes #234 and #453
  src/hammer-vlsi/cli_driver_test.py
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/hammer_vlsi/cli_driver.py
  src/hammer-vlsi/hammer_vlsi/driver.py
  src/hammer-vlsi/hammer_vlsi/hammer_build_systems.py
  src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
Labels: CurrentTapeout, advanced PR, hierarchical, medium priority, usability

#463 Canonicalize the input file paths
  src/hammer-vlsi/hammer_vlsi/cli_driver.py
Labels: bug, medium priority
