Repository ucb-bar/hammer, pull requests merged in 2022-05, with the labels that each got.

#645 Fix ASAP7 SRAMs
  src/hammer-vlsi/technology/asap7/sram_compiler/__init__.py
  src/hammer-vlsi/technology/asap7/sram_compiler/memories/behavioral/sram_behav_models.v
  src/hammer-vlsi/test.py
Labels: bug, high priority

#651 Formal Verification (LEC at first)
  doc/Hammer-Flow/Formal.rst
  doc/Hammer-Flow/index.rst
  src/hammer-tech/hammer_tech.py
  src/hammer-vlsi/cli_driver_test.py
  src/hammer-vlsi/defaults.yml
  src/hammer-vlsi/generate_properties.py
  src/hammer-vlsi/hammer_vlsi/cli_driver.py
  src/hammer-vlsi/hammer_vlsi/driver.py
  src/hammer-vlsi/hammer_vlsi/hammer_build_systems.py
  src/hammer-vlsi/hammer_vlsi/hammer_tool.py
  src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
  src/test/mypy.sh
Labels: enhancement

#655 add type-checking to configuration files
  doc/Hammer-Use/Hammer-Config.rst
  doc/Technology/Tech-defaults.rst
  src/hammer-vlsi/defaults_types.yml
  src/hammer_config/config_src.py
  src/hammer_config_test/test.py
Labels: enhancement, usability
