Repository ucb-bar/hammer, pull requests merged in 2023-11, with the labels that each got.

#817 hammer logging fixes
  hammer/logging/logging.py
  hammer/vlsi/driver.py
Labels: bug

#818 Clock & Delay constraint refinements
  hammer/config/defaults.yml
  hammer/synthesis/yosys/__init__.py
  hammer/vlsi/constraints.py
  hammer/vlsi/hammer_tool.py
  hammer/vlsi/hammer_vlsi_impl.py
  hammer/vlsi/vendor/openroad.py
  tests/test_constraints.py
Labels: SDC

#824 Add make clean
  e2e/Makefile
  hammer/synthesis/genus/__init__.py
Labels: very low priority
