Repository ucb-bar/hammer, pull requests merged in 2023-03, with the labels that each got.

#712 Bottom-up hierarchical diagram
  doc/Hammer-Use/Hierarchical.rst
  doc/Hammer-Use/hier.d2
  doc/Hammer-Use/hier.svg
Labels: hierarchical, documentation

#710 Check + dump power straps abutting/over hardmacros
  hammer/config/defaults.yml
  hammer/config/defaults_types.yml
  hammer/vlsi/hammer_vlsi_impl.py
Labels: enhancement, usability

#729 Issue & PR templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#731 Fix readthedocs pages for plugins
  .github/PULL_REQUEST_TEMPLATE.md
  doc/CAD-Tools/OpenROAD.md
  doc/CAD-Tools/OpenROAD.rst
  doc/Technology/ASAP7.md
  doc/Technology/ASAP7.rst
  doc/Technology/Nangate45.md
  doc/Technology/Nangate45.rst
  doc/Technology/Sky130.md
  doc/Technology/Sky130.rst
Labels: bug

#733 Add missing keys to defaults
  hammer/config/defaults.yml
  hammer/config/defaults_types.yml
Labels: bug

#774 add config to recognize marker
  pytest.ini
Labels: bug
